### ISSUE TITLE
Make the simple output look more sexy and colorful

### ISSUE THREAD

**Issue by SkyperTHC** [messede-degod/sstable-migrator#6]
that's `curl -fL https://ip.thc.org/1.1.1.1`-style requests:

![Screenshot 2024-08-10 at 11 19 09](https://github.com/user-attachments/assets/9da245d2-a04c-439a-8bec-a2900864cb9e)

Should also show if the output has been cut-short because of default limit being 5 (? or is it 1?) and a hint how to overcome this limit (e.g. `?l=100000` or `?l=0` etc)

**Comment by messede-degod** [comment]
CLI Friendly Simple Output is now available
